### ISSUE TITLE
Upgrade to jQuery UI 1.11

### ISSUE THREAD

**Issue by brunomperes** [angular-ui/ui-slider#87]

**Comment by PowerKiKi** [comment]
Create a PR for improvements you may want to see.

**Comment by brunomperes** [comment]
I don't understand why the issue was closed.
Shouldn't it be closed after a follow-up ? And thus the PR would close it ?

**Comment by PowerKiKi** [comment]
The original issue was not constructive. It did not explain why it should be upgraded, what kind of problems it would solve, or what benefit we could get from upgrading. Nor does this contains any code to to the actual upgrade (that would be a PR).

Since we have so little resources to take care of those projects, "trivial" issue like this one will not be kept opened. This is to avoid being overwhelmed by a huge number of opened issues. There are a lot of "should" and "could" that we could open issues for, but unless there is a real will to make it happen it the foreseeable future, it is not worth opening issues that will be kept opened for months/years.

Don't get me wrong, I don't think upgrading is a bad idea, but this specific issue is not helping anyone.
